name: Check firmware update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  push:

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - model: "SCG27"
            csc: "KDI"
            omc: "QBI"
            imei: "352727291127191"
          - model: "SC-53C"
            csc: "DCM"
            omc: "DCM"
            imei: "358542660183871"
          - model: "SC-53E"
            csc: "DCM"
            omc: "QCM"
            imei: "350481991085596"
          - model: "SM-A146B"
            csc: "INS"
            omc: "ODM"
            imei: "351733712227777"
          - model: "SM-A146M"
            csc: "ZTO"
            omc: "OWO"
            imei: "356969672920630"
          - model: "SM-A1660"
            csc: "BRI"
            omc: "OZS"
            imei: "350388933286556"
          - model: "SM-A1660"
            csc: "TGY"
            omc: "OZS"
            imei: "350388933286556"
          - model: "SM-A166B"
            csc: "EUX"
            omc: "OXM"
            imei: "352623171813515"
          - model: "SM-A166E"
            csc: "MID"
            omc: "OJM"
            imei: "350079260654686"
          - model: "SM-A166M"
            csc: "ARO"
            omc: "OWO"
            imei: "358897900269868"
          - model: "SM-A166M"
            csc: "TPA"
            omc: "OWO"
            imei: "358897900269868"
          - model: "SM-A166M"
            csc: "ZTO"
            omc: "OWO"
            imei: "358897900269868"
          - model: "SM-A176B"
            csc: "EUX"
            omc: "OXM"
            imei: "358224900211123"
          - model: "SM-A2560"
            csc: "TGY"
            omc: "TGY"
            imei: "359681860424922"
          - model: "SM-A256B"
            csc: "EUX"
            omc: "OXM"
            imei: "356513701234561"
          - model: "SM-A256E"
            csc: "INS"
            omc: "ODM"
            imei: "359665753099560"
          - model: "SM-A256E"
            csc: "TPA"
            omc: "OWO"
            imei: "359665753099560"
          - model: "SM-A256N"
            csc: "KOO"
            omc: "OKR"
            imei: "352168410552086"
          - model: "SM-A266B"
            csc: "EUX"
            omc: "OXM"
            imei: "350439764296683"
          - model: "SM-A266M"
            csc: "TPA"
            omc: "OWO"
            imei: "350601361078943"
          - model: "SM-A3360"
            csc: "TGY"
            omc: "TGY"
            imei: "352332770123454"
          - model: "SM-A336B"
            csc: "EUX"
            omc: "OXM"
            imei: "350731010310817"
          - model: "SM-A336E"
            csc: "INS"
            omc: "ODM"
            imei: "353475124959005"
          - model: "SM-A336M"
            csc: "ARO"
            omc: "OWO"
            imei: "358076931517575"
          - model: "SM-A336M"
            csc: "ZTO"
            omc: "OWO"
            imei: "351326801234562"
          - model: "SM-A336N"
            csc: "KOO"
            omc: "OKR"
            imei: "352861162429095"
          - model: "SM-A356B"
            csc: "EUX"
            omc: "OXM"
            imei: "351165709024463"
          - model: "SM-A356E"
            csc: "INS"
            omc: "ODM"
            imei: "357435842581255"
          - model: "SM-A356E"
            csc: "TPA"
            omc: "OWO"
            imei: "357435842581255"
          - model: "SM-A5360"
            csc: "CHC"
            omc: "CHC"
            imei: "353418791234567"
          - model: "SM-A536B"
            csc: "EUX"
            omc: "OXM"
            imei: "350498050045386"
          - model: "SM-A536B"
            csc: "VIP"
            omc: "OXM"
            imei: "350498050045386"
          - model: "SM-A536E"
            csc: "INS"
            omc: "ODM"
            imei: "357518816398424"
          - model: "SM-A536E"
            csc: "PGU"
            omc: "OWA"
            imei: "357518816398424"
          - model: "SM-A536E"
            csc: "TPA"
            omc: "OWO"
            imei: "357518816398424"
          - model: "SM-A536N"
            csc: "KOO"
            omc: "OKR"
            imei: "350815361829549"
          - model: "SM-A5460"
            csc: "CHC"
            omc: "CHC"
            imei: "357733314742433"
          - model: "SM-A546B"
            csc: "EUX"
            omc: "OXM"
            imei: "350756481692245"
          - model: "SM-A546E"
            csc: "EGY"
            omc: "OJM"
            imei: "350090711234564"
          - model: "SM-A546S"
            csc: "SKC"
            omc: "SKC"
            imei: "351992292910349"
          - model: "SM-A5560"
            csc: "CHC"
            omc: "CHC"
            imei: "356394418761364"
          - model: "SM-A556B"
            csc: "EUX"
            omc: "OXM"
            imei: "352773711457693"
          - model: "SM-A556E"
            csc: "INS"
            omc: "ODM"
            imei: "355326621234566"
          - model: "SM-A556E"
            csc: "TPA"
            omc: "OWO"
            imei: "355326621234566"
          - model: "SM-A556E"
            csc: "PGU"
            omc: "OWA"
            imei: "355326621234566"
          - model: "SM-A556S"
            csc: "SKC"
            omc: "SKC"
            imei: "351229821198959"
          - model: "SM-A5660"
            csc: "TGY"
            omc: "OZS"
            imei: "354538860252130"
          - model: "SM-A566B"
            csc: "EUX"
            omc: "OXM"
            imei: "353632422617129"
          - model: "SM-A566E"
            csc: "INS"
            omc: "ODM"
            imei: "357369474252622"
          - model: "SM-E146B"
            csc: "INS"
            omc: "ODM"
            imei: "356412381282885"
          - model: "SM-E346B"
            csc: "INS"
            omc: "ODM"
            imei: "350134240145972"
          - model: "SM-M336B"
            csc: "EUX"
            omc: "OXM"
            imei: "353647612234865"
          - model: "SM-M336BU"
            csc: "INS"
            omc: "ODM"
            imei: "354595808618376"
          - model: "SM-M336K"
            csc: "KTC"
            omc: "KTC"
            imei: "352961654039491"
          - model: "SM-M346B1"
            csc: "XEO"
            omc: "OXM"
            imei: "353257871234562"
          - model: "SM-M346B2"
            csc: "TUR"
            omc: "OJM"
            imei: "353903640123459"
          - model: "SM-M346B"
            csc: "INS"
            omc: "ODM"
            imei: "350886063201709"
          - model: "SM-M346B"
            csc: "ZTO"
            omc: "OWO"
            imei: "350886063201709"
          - model: "SM-M356B"
            csc: "INS"
            omc: "ODM"
            imei: "353154435977846"
          - model: "SM-M366B"
            csc: "INS"
            omc: "ODM"
            imei: "354931770115549"
          - model: "SM-M566B"
            csc: "INS"
            omc: "ODM"
            imei: "352572130804547"
          - model: "SM-P620"
            csc: "EUX"
            omc: "OXM"
            serial: "R52Y1082J0Y"
          - model: "SM-P625"
            csc: "EUX"
            omc: "OXM"
            serial: "R52X506ETTN"
          - model: "SM-S901B"
            csc: "EUX"
            omc: "OXM"
            imei: "350330053121965"
          - model: "SM-S906B"
            csc: "EUX"
            omc: "OXM"
            imei: "353055522360541"
          - model: "SM-S908B"
            csc: "EUX"
            omc: "OXM"
            imei: "353074281716249"
          - model: "SM-X520"
            csc: "EUX"
            omc: "OXM"
            serial: "R52Y307AKNH"
          - model: "SM-X526B"
            csc: "EUX"
            omc: "OXM"
            imei: "356160460693130"
          - model: "SM-X616B"
            csc: "EUX"
            omc: "OXM"
            imei: "354178380788816"
          - model: "SM-X620"
            csc: "EUX"
            omc: "OXM"
            serial: "R52Y307JRVF"

    concurrency:
      group: "update-${{ matrix.model }}-${{ matrix.csc }}-${{ github.ref }}"
      cancel-in-progress: true
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compare latest version with current version
        env:
          MODEL: ${{ matrix.model }}
          CSC: ${{ matrix.csc }}
          OMC: ${{ matrix.omc }}
        run: |
          ./scripts/compare_firmware.sh

      - name: Cleanup space (1/2)
        if: env.update == 1
        run: |
          sudo apt-get remove --purge -y "php*" "dotnet*" "mysql*" "nodejs*" "clang*" "google*"
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo docker image prune --all --force
          sudo docker builder prune -a
          sudo rm -rf /usr/share/dotnet /usr/local /opt/ghc /opt/hostedtoolcache/CodeQL

      - name: Install dependencies
        if: env.update == 1
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync liblz4-tool zip android-sdk-libsparse-utils f2fs-tools linux-modules-extra-$(uname -r) python3 python3-venv unzip gh
          sudo modprobe f2fs

      - name: Get firmware
        if: env.update == 1
        env:
          MODEL: ${{ matrix.model }}
          CSC: ${{ matrix.csc }}
          IMEI: ${{ matrix.imei }}
          SERIAL: ${{ matrix.serial }}
        run: |
          ./scripts/fetch_firmware.sh

      - name: Get path of files
        if: env.update == 1
        run: |
          ./scripts/get_path.sh

      - name: Cleanup space (2/3)
        if: env.update == 1
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Cleanup space (2/3)
        if: env.update == 1
        uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: 'compiler_cmake'

      - name: Set Swap Space
        if: env.update == 1
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 20

      - name: Extract kernel images
        if: env.update == 1
        env:
          AP_TAR: ${{ env.ap_tar }}
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
        run: |
          ./scripts/kernel.sh

      - name: Extract PIT file
        if: env.update == 1
        run: |
          tar --wildcards --exclude='*/*' -xvf ${{ env.csc_tar }} '*.pit'
          echo "pit_file=`find -name *.pit`" >> $GITHUB_ENV

      - name: Generate patched vbmeta
        if: env.update == 1
        env:
          AP_TAR: ${{ env.ap_tar }}
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
        run: |
          ./scripts/vbmeta.sh

      - name: Extract vendor partition
        if: env.update == 1
        env:
          MODEL: ${{ matrix.model }}
          AP_TAR: ${{ env.ap_tar }}
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
        run: |
          ./scripts/vendor.sh

      - name: Get some blobs
        if: env.update == 1
        env:
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
        run: |
          ./scripts/blobs.sh
           
      - name: Generate proprietary-files.txt
        if: env.update == 1
        env:
          MODEL: ${{ matrix.model }}
          BOARD: ${{ env.board }}
          OMC: ${{ matrix.omc }}
          CSC: ${{ matrix.csc }}
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
        run: |
          ./scripts/proprietary-files.sh

      - name: Generate proprietary-firmware.txt
        if: env.update == 1
        env:
          MODEL: ${{ matrix.model }}
          BOARD: ${{ env.board }}
          OMC: ${{ matrix.omc }}
          CSC: ${{ matrix.csc }}
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
          BL_TAR: ${{ env.bl_tar }}
          CP_TAR: ${{ env.cp_tar }}
        run: |
          ./scripts/proprietary-firmware.sh

      - name: Generate file_context
        if: env.update == 1
        env:
          MODEL: ${{ matrix.model }}
          BOARD: ${{ env.board }}
          CSC: ${{ matrix.csc }}
          OMC: ${{ matrix.omc }}
        run: |
          ./scripts/file_context.sh
      
      - name: Generate fs_config
        if: env.update == 1
        env:
          MODEL: ${{ matrix.model }}
          BOARD: ${{ env.board }}
          CSC: ${{ matrix.csc }}
          OMC: ${{ matrix.omc }}
        run: |
          ./scripts/fs_config.sh

      - name: Generate versions.txt
        if: env.update == 1
        env:
          AP_TAR: ${{ env.ap_tar }}
          BL_LOCK: ${{ env.bl_lock }}
          CSC_TAR: ${{ env.csc_tar }}
          MODEL: ${{ matrix.model }}
          CSC: ${{ matrix.csc }}
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
          LATEST_CSCVERSION: ${{ env.latest_cscversion }}
        run: |
          ./scripts/versions.sh

      - name: Update current version
        if: env.update == 1
        env:
          MODEL: ${{ matrix.model }}
          BOARD: ${{ env.board }}
          OMC: ${{ matrix.omc }}
          CSC: ${{ matrix.csc }}
          LATEST_VERSION: ${{ env.latest_version }}
          LATEST_SHORTVERSION: ${{ env.latest_shortversion }}
          GHF: ${{ github.ref }}
        run: |
          sudo apt install -y gh
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          ./scripts/git.sh

      - name: Push changes to repo
        if: env.update == 1
        uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Upload release assets
        if: env.update == 1
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: versions.txt
          tag_name: "${{ env.latest_shortversion }}_${{ matrix.csc }}_${{ matrix.omc }}"
          name: "${{ env.latest_shortversion }} - ${{ matrix.model }} - ${{ matrix.csc }} - ${{ matrix.omc }}"
          files: |
            ${{ env.bl_tar }}
            ${{ env.cp_tar }}
            ${{ env.home_csc_tar }}
            ${{ env.latest_shortversion }}_kernel.tar
            ${{ env.pit_file }}
            ${{ env.latest_shortversion }}_patched_vbmeta.tar
            ${{ env.latest_shortversion }}_vendor.zip
            ${{ env.latest_shortversion }}_vendor-extracted.zip
            ${{ env.latest_shortversion }}_firmware_tee.zip
            ${{ env.latest_shortversion }}_BL_CP-los.zip
            ${{ env.latest_shortversion}}_vendor.prop
